// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7S4tK_MrCbFTRIuacdIMoj-xRs8DpdRE',
    appId: '1:966315458805:web:612b31e0511fd2501485bc',
    messagingSenderId: '966315458805',
    projectId: 'tut-rivaan-instagram',
    authDomain: 'tut-rivaan-instagram.firebaseapp.com',
    storageBucket: 'tut-rivaan-instagram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb66tRjQneT4tete9dn92GglvALls-r6w',
    appId: '1:966315458805:android:921a25b6ae9f634f1485bc',
    messagingSenderId: '966315458805',
    projectId: 'tut-rivaan-instagram',
    storageBucket: 'tut-rivaan-instagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNWxNY6uYdYrTbVrjx4lgURJcHHbmoyyE',
    appId: '1:966315458805:ios:2d4efd75b8b2b7e81485bc',
    messagingSenderId: '966315458805',
    projectId: 'tut-rivaan-instagram',
    storageBucket: 'tut-rivaan-instagram.appspot.com',
    iosClientId: '966315458805-m1bukhuij1nbbcft82ruarv5djv8fbaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramRivaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNWxNY6uYdYrTbVrjx4lgURJcHHbmoyyE',
    appId: '1:966315458805:ios:49936be8d74ca6921485bc',
    messagingSenderId: '966315458805',
    projectId: 'tut-rivaan-instagram',
    storageBucket: 'tut-rivaan-instagram.appspot.com',
    iosClientId: '966315458805-l5ca2khfr2dll0seq5lvkld8lh0j1he9.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramRivaan.RunnerTests',
  );
}
